# Generated by Django 5.1.3 on 2024-11-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provedores',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=50)),
                ('idproductos', models.CharField(max_length=25)),
                ('Precio', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=50)),
            ],
        ),
    ]
